# action.yml
name: 'ECS deploy'
description: 'Github action using fabfuel/ecs-deploy script for ecs deployments'
inputs:
    cluster:
        description: 'Cluster name where service/task will be deployed'
        required: true
    service:
        description: 'Service name of the service/task to be deployed'
        required: true
    task:
        description: 'Task definition name to be updated'
        required: true
    containers:
        description: 'Container names to be updated separated by space'
        required: true
    envfile:
        description: 'Env file path'
        required: false
    timeout:
        description: 'Deployment timeout (default 300)'
        required: false

runs:
    using: 'docker'
    image: 'Dockerfile'
    args:
        - ${{ inputs.cluster }}
        - ${{ inputs.service }}
        - ${{ inputs.task }}
        - ${{ inputs.containers }}
        - ${{ inputs.envfile }}
        - ${{ inputs.timeout }}
